openapi: 3.0.0
info:
  title: Coding challenge API
  description: Coding challenge API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /questions:
    get:
      tags:
        - Questions
      summary: Returns questions
      description: Returns all the questions
      parameters:
        - name: id
          in: path
          description: question id
          schema:
            type: string
            maxLength: 24
            minLength: 24
            pattern: ^[0-9a-f]{24}$
        - name: page
          in: query
          description: Page setup offset for search.
          schema:
            type: number
      responses:
        '200':
          description: Questions data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: User name
                    email:
                      type: string
                      format: email
                      description: User email
                    observations:
                      type: string
                      description: User observations
                    date:
                      type: string
                      pattern: ([0-9]{4})-([0-9]{2})-([0-9]{2})
                      example: 2022-05-04
                      description: Date of creation
